"""initial v3 schema

Revision ID: 4b0d444f4e53
Revises: None
Create Date: 2026-07-22 03:05:13.805472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b0d444f4e53'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('doc_type', sa.String(length=50), nullable=True, comment='circular | note | contract | kyc_dossier | credit_dossier'),
    sa.Column('number', sa.String(length=50), nullable=True, comment='Circular number from BCT (e.g., 2024-01). Null for non-circulars.'),
    sa.Column('circular_reference', sa.String(length=100), nullable=True, comment='Alias for number — kept for v2 compatibility'),
    sa.Column('date_issued', sa.Date(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True, comment='SHA-256 for deduplication'),
    sa.Column('status', sa.String(length=50), nullable=True, comment='ACTIVE | MODIFIED | ABROGATED'),
    sa.Column('indexation_state', sa.String(length=50), nullable=True, comment='PENDING | PROCESSING | INDEXED | FAILED'),
    sa.Column('language', sa.String(length=10), nullable=True, comment='fr | ar | fr-ar'),
    sa.Column('raw_text', sa.Text(), nullable=True, comment='Full extracted text for reprocessing'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False, comment='One of: admin, compliance, legal, credit, user'),
    sa.Column('department', sa.String(length=100), nullable=True, comment='Organizational department (e.g., Direction Conformité)'),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False, comment='e.g., DOCUMENT_UPLOADED, CHAT_MESSAGE_SENT, KYC_CHECK_RUN'),
    sa.Column('entity_type', sa.String(length=50), nullable=True, comment='document, chat, kyc, contract, credit'),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('endpoint', sa.String(length=200), nullable=True, comment='HTTP method + path, e.g., POST /api/chat/message'),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='Client IP (IPv4 or IPv6)'),
    sa.Column('input_hash', sa.String(length=64), nullable=True, comment='SHA-256 of the request body for tamper detection'),
    sa.Column('output_summary', sa.Text(), nullable=True, comment='Truncated response summary (first 500 chars)'),
    sa.Column('details_json', sa.Text(), nullable=True, comment='Full JSON details'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chunks',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('section_title', sa.String(length=300), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('embedding_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversation_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('impact_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_circular_id', sa.String(length=36), nullable=False, comment='The new circular that triggered the impact analysis'),
    sa.Column('source_circular_ref', sa.String(length=100), nullable=False, comment='Circular reference (e.g., 2025-03) for quick display'),
    sa.Column('affected_entity_type', sa.String(length=50), nullable=False, comment='obligation | process | contract_template | circular'),
    sa.Column('affected_entity_id', sa.String(length=100), nullable=False, comment='Neo4j node ID or reference of the affected entity'),
    sa.Column('affected_entity_name', sa.String(length=500), nullable=True, comment='Human-readable name of the affected entity'),
    sa.Column('severity', sa.String(length=20), nullable=False, comment='LOW | MEDIUM | HIGH | CRITICAL'),
    sa.Column('impact_description', sa.Text(), nullable=True, comment='LLM-generated description of the impact'),
    sa.Column('relationship_path', sa.Text(), nullable=True, comment='JSON-serialized path from source circular to affected entity'),
    sa.Column('is_acknowledged', sa.Boolean(), nullable=True, comment='Whether a compliance officer has reviewed this impact'),
    sa.Column('acknowledged_by', sa.String(length=36), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_circular_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversation_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False, comment='user | assistant'),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sources_json', sa.Text(), nullable=True, comment='JSON-serialized sources'),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['conversation_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conversation_messages')
    op.drop_table('impact_records')
    op.drop_table('conversation_sessions')
    op.drop_table('chunks')
    op.drop_table('audit_logs')
    op.drop_table('users')
    op.drop_table('documents')
    # ### end Alembic commands ###
